export const LOUISVILLE_CENTER = [38.2527, -85.7585];
export const DEFAULT_ZOOM = 12;

export const CATEGORY_CONFIG = {
  festival: { label: "Festival", emoji: "🎪", color: "#e67e22" },
  outdoor: { label: "Outdoor", emoji: "🌳", color: "#27ae60" },
  sports: { label: "Sports", emoji: "⚽", color: "#3498db" },
  arts: { label: "Arts & Culture", emoji: "🎨", color: "#9b59b6" },
  music: { label: "Music", emoji: "🎵", color: "#e74c3c" },
  food: { label: "Food & Drink", emoji: "🍔", color: "#f39c12" },
  holiday: { label: "Holiday", emoji: "🎉", color: "#e91e63" },
  community: { label: "Community", emoji: "🤝", color: "#00bcd4" },
  education: { label: "Education", emoji: "📚", color: "#607d8b" },
  attraction: { label: "Attraction", emoji: "🎢", color: "#ff5722" },
  trick_or_treat: { label: "Trick or Treat", emoji: "🎃", color: "#ff6f00" },
  fireworks: { label: "Fireworks", emoji: "🎆", color: "#1a237e" },
  santa: { label: "Santa", emoji: "🎅", color: "#c62828" },
  easter: { label: "Easter", emoji: "🐣", color: "#81c784" },
  parade: { label: "Parade", emoji: "🏳️‍🌈", color: "#ab47bc" },
  other: { label: "Other", emoji: "📌", color: "#78909c" },
};

export const HOLIDAY_CONFIG = {
  none: { label: "None", emoji: "" },
  july_4th: { label: "July 4th", emoji: "🇺🇸", color: "#1565c0" },
  halloween: { label: "Halloween", emoji: "🎃", color: "#ff6f00" },
  christmas: { label: "Christmas", emoji: "🎄", color: "#c62828" },
  easter: { label: "Easter", emoji: "🐣", color: "#81c784" },
  st_patricks: { label: "St. Patrick's", emoji: "☘️", color: "#2e7d32" },
  thanksgiving: { label: "Thanksgiving", emoji: "🦃", color: "#8d6e63" },
  new_years: { label: "New Year's", emoji: "🎊", color: "#6a1b9a" },
  valentines: { label: "Valentine's", emoji: "💕", color: "#e91e63" },
  memorial_day: { label: "Memorial Day", emoji: "🇺🇸", color: "#37474f" },
  labor_day: { label: "Labor Day", emoji: "👷", color: "#455a64" },
};

export const AGE_RANGES = [
  { label: "Babies (0-2)", min: 0, max: 2 },
  { label: "Toddlers (2-5)", min: 2, max: 5 },
  { label: "Kids (5-10)", min: 5, max: 10 },
  { label: "Tweens (10-13)", min: 10, max: 13 },
  { label: "Teens (13-18)", min: 13, max: 18 },
  { label: "All Ages", min: 0, max: 18 },
];

export const PERMANENT_ATTRACTIONS = [
  {
    title: "Louisville Zoo",
    description: "Home to over 1,700 animals from around the world. Features a splash park, rides, and seasonal events like the Louisville Zoo's Halloween party and holiday lights.",
    latitude: 38.2100,
    longitude: -85.7178,
    address: "1100 Trevilian Way, Louisville, KY 40213",
    category: "attraction",
    is_permanent: true,
    is_free: false,
    price_info: "$17-22 adults, $12-15 kids",
    age_min: 0,
    age_max: 18,
    website_url: "https://louisvillezoo.org",
    photos: ["https://images.unsplash.com/photo-1534567153574-2b12153a87f0?w=800&h=500&fit=crop"],
  },
  {
    title: "Kentucky Kingdom",
    description: "Thrilling rides, water park, and family-friendly entertainment. Features roller coasters, kiddie rides, and Hurricane Bay water park.",
    latitude: 38.1983,
    longitude: -85.7425,
    address: "937 Phillips Ln, Louisville, KY 40209",
    category: "attraction",
    is_permanent: true,
    is_free: false,
    price_info: "$39.95+ per person",
    age_min: 3,
    age_max: 18,
    website_url: "https://www.kentuckykingdom.com",
    photos: ["https://images.unsplash.com/photo-1536768139911-e290a59ddb72?w=800&h=500&fit=crop"],
  },
  {
    title: "Louisville Slugger Museum",
    description: "The world's largest baseball bat greets you at this legendary museum. Learn the history of America's pastime and watch bats being made.",
    latitude: 38.2588,
    longitude: -85.7632,
    address: "800 W Main St, Louisville, KY 40202",
    category: "attraction",
    is_permanent: true,
    is_free: false,
    price_info: "$18 adults, $11 kids",
    age_min: 3,
    age_max: 18,
    website_url: "https://www.sluggermuseum.com",
    photos: ["https://images.unsplash.com/photo-1529768167801-9173d94c2a42?w=800&h=500&fit=crop"],
  },
  {
    title: "Louisville Mega Cavern",
    description: "An underground adventure park in a former limestone mine. Features zip lines, ropes courses, bike park, tram tours, and seasonal attractions like Lights Under Louisville.",
    latitude: 38.2021,
    longitude: -85.7235,
    address: "1841 Taylor Ave, Louisville, KY 40213",
    category: "attraction",
    is_permanent: true,
    is_free: false,
    price_info: "$25-45 per activity",
    age_min: 3,
    age_max: 18,
    website_url: "https://louisvillemegacavern.com",
    photos: ["https://images.unsplash.com/photo-1504870712474-3df5c2f16a83?w=800&h=500&fit=crop"],
  },
  {
    title: "Kentucky Science Center",
    description: "Three floors of interactive exhibits designed to make science fun for kids of all ages. Features a digital theater and rotating exhibitions.",
    latitude: 38.2565,
    longitude: -85.7595,
    address: "727 W Main St, Louisville, KY 40202",
    category: "education",
    is_permanent: true,
    is_free: false,
    price_info: "$15 adults, $13 kids",
    age_min: 2,
    age_max: 18,
    website_url: "https://kysciencecenter.org",
    photos: ["https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=500&fit=crop"],
  },
];