/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CitiesRouteImport } from './routes/cities'
import { Route as CreateRouteImport } from './routes/create'
import { Route as HolidaysRouteImport } from './routes/holidays'
import { Route as NeighborhoodsRouteImport } from './routes/neighborhoods'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as EventIdRouteImport } from './routes/event.$id'
import { Route as HolidaysChristmasRouteImport } from './routes/holidays.christmas'
import { Route as HolidaysHalloweenRouteImport } from './routes/holidays.halloween'
import { Route as ApiCronSyncRouteImport } from './routes/api/cron/sync'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesRoute = CitiesRouteImport.update({
  id: '/cities',
  path: '/cities',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const HolidaysRoute = HolidaysRouteImport.update({
  id: '/holidays',
  path: '/holidays',
  getParentRoute: () => rootRouteImport,
} as any)
const NeighborhoodsRoute = NeighborhoodsRouteImport.update({
  id: '/neighborhoods',
  path: '/neighborhoods',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const EventIdRoute = EventIdRouteImport.update({
  id: '/event/$id',
  path: '/event/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HolidaysChristmasRoute = HolidaysChristmasRouteImport.update({
  id: '/christmas',
  path: '/christmas',
  getParentRoute: () => HolidaysRoute,
} as any)
const HolidaysHalloweenRoute = HolidaysHalloweenRouteImport.update({
  id: '/halloween',
  path: '/halloween',
  getParentRoute: () => HolidaysRoute,
} as any)
const ApiCronSyncRoute = ApiCronSyncRouteImport.update({
  id: '/api/cron/sync',
  path: '/api/cron/sync',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cities': typeof CitiesRoute
  '/create': typeof CreateRoute
  '/holidays': typeof HolidaysRouteWithChildren
  '/neighborhoods': typeof NeighborhoodsRoute
  '/saved': typeof SavedRoute
  '/event/$id': typeof EventIdRoute
  '/holidays/christmas': typeof HolidaysChristmasRoute
  '/holidays/halloween': typeof HolidaysHalloweenRoute
  '/api/cron/sync': typeof ApiCronSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cities': typeof CitiesRoute
  '/create': typeof CreateRoute
  '/holidays': typeof HolidaysRouteWithChildren
  '/neighborhoods': typeof NeighborhoodsRoute
  '/saved': typeof SavedRoute
  '/event/$id': typeof EventIdRoute
  '/holidays/christmas': typeof HolidaysChristmasRoute
  '/holidays/halloween': typeof HolidaysHalloweenRoute
  '/api/cron/sync': typeof ApiCronSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cities': typeof CitiesRoute
  '/create': typeof CreateRoute
  '/holidays': typeof HolidaysRouteWithChildren
  '/neighborhoods': typeof NeighborhoodsRoute
  '/saved': typeof SavedRoute
  '/event/$id': typeof EventIdRoute
  '/holidays/christmas': typeof HolidaysChristmasRoute
  '/holidays/halloween': typeof HolidaysHalloweenRoute
  '/api/cron/sync': typeof ApiCronSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cities'
    | '/create'
    | '/holidays'
    | '/neighborhoods'
    | '/saved'
    | '/event/$id'
    | '/holidays/christmas'
    | '/holidays/halloween'
    | '/api/cron/sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cities'
    | '/create'
    | '/holidays'
    | '/neighborhoods'
    | '/saved'
    | '/event/$id'
    | '/holidays/christmas'
    | '/holidays/halloween'
    | '/api/cron/sync'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cities'
    | '/create'
    | '/holidays'
    | '/neighborhoods'
    | '/saved'
    | '/event/$id'
    | '/holidays/christmas'
    | '/holidays/halloween'
    | '/api/cron/sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CitiesRoute: typeof CitiesRoute
  CreateRoute: typeof CreateRoute
  HolidaysRoute: typeof HolidaysRouteWithChildren
  NeighborhoodsRoute: typeof NeighborhoodsRoute
  SavedRoute: typeof SavedRoute
  EventIdRoute: typeof EventIdRoute
  ApiCronSyncRoute: typeof ApiCronSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities': {
      id: '/cities'
      path: '/cities'
      fullPath: '/cities'
      preLoaderRoute: typeof CitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holidays': {
      id: '/holidays'
      path: '/holidays'
      fullPath: '/holidays'
      preLoaderRoute: typeof HolidaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neighborhoods': {
      id: '/neighborhoods'
      path: '/neighborhoods'
      fullPath: '/neighborhoods'
      preLoaderRoute: typeof NeighborhoodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$id': {
      id: '/event/$id'
      path: '/event/$id'
      fullPath: '/event/$id'
      preLoaderRoute: typeof EventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holidays/christmas': {
      id: '/holidays/christmas'
      path: '/christmas'
      fullPath: '/holidays/christmas'
      preLoaderRoute: typeof HolidaysChristmasRouteImport
      parentRoute: typeof HolidaysRoute
    }
    '/holidays/halloween': {
      id: '/holidays/halloween'
      path: '/halloween'
      fullPath: '/holidays/halloween'
      preLoaderRoute: typeof HolidaysHalloweenRouteImport
      parentRoute: typeof HolidaysRoute
    }
    '/api/cron/sync': {
      id: '/api/cron/sync'
      path: '/api/cron/sync'
      fullPath: '/api/cron/sync'
      preLoaderRoute: typeof ApiCronSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HolidaysRouteChildren {
  HolidaysChristmasRoute: typeof HolidaysChristmasRoute
  HolidaysHalloweenRoute: typeof HolidaysHalloweenRoute
}

const HolidaysRouteChildren: HolidaysRouteChildren = {
  HolidaysChristmasRoute: HolidaysChristmasRoute,
  HolidaysHalloweenRoute: HolidaysHalloweenRoute,
}

const HolidaysRouteWithChildren = HolidaysRoute._addFileChildren(
  HolidaysRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CitiesRoute: CitiesRoute,
  CreateRoute: CreateRoute,
  HolidaysRoute: HolidaysRouteWithChildren,
  NeighborhoodsRoute: NeighborhoodsRoute,
  SavedRoute: SavedRoute,
  EventIdRoute: EventIdRoute,
  ApiCronSyncRoute: ApiCronSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
